# frontend/Gemfile

source "https://rubygems.org"
git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }

ruby ">=3.2.2"

gem "rails", "~> 7.1.3"
gem "puma", "~> 6.4"
gem "newrelic_rpm"