services:
  webapp:
    build: ./app
    container_name: adventureworks_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_SERVER=mssql # Connect to the mssql service name
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=${PROJECT_PREFIX}-app
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - app-network

  locust:
    build: ./app
    container_name: adventureworks_locust
    restart: always
    ports:
      - "8089:8089"
    command: locust -f /app/locustfile.py --host http://webapp:5000 --web-port 8089
    depends_on:
      - webapp
    networks:
      - app-network

  mssql:
    build: ./mssql
    container_name: adventureworks_db
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"${MSSQL_SA_PASSWORD}\" -Q \"SELECT DB_NAME(2)\" | grep -q tempdb"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 3m

volumes:
  mssql-data:

networks:
  app-network:

